import { execFile, type ExecFileException, type ExecFileOptionsWithStringEncoding } from "node:child_process";
import path from "node:path";

import type { ManagedNode } from "../packages/contracts/src/inventory.js";
import { assertValidation, normalizeNode } from "./bird-normalize-common.js";
import type { AgentBroker } from "./agent-broker.js";
import { errorContext, logger } from "./logger.js";

/**
 * The maximum amount of shell source accepted by the legacy SSH transport.
 * Runtime operations are generated by Birdbox itself; this bound prevents a
 * future caller from turning the transport into an unbounded command pipe.
 */
export const MAX_NODE_COMMAND_LENGTH = 256 * 1024;
export const MAX_NODE_INPUT_LENGTH = 16 * 1024 * 1024;
export const MAX_NODE_TIMEOUT = 120_000;
export const MAX_NODE_OUTPUT = 8 * 1024 * 1024;

export interface NodeExecutorOptions {
  timeout?: number;
  maxBuffer?: number;
  input?: string;
}

export interface NodeCommandResult {
  ok: boolean;
  stdout: string;
  stderr: string;
  code?: string | number;
}

/**
 * Dispatch a structured operation to an outbound Agent.  The legacy command
 * executor deliberately remains separate so SSH/local nodes keep their
 * existing compatibility path and no RPC caller can smuggle shell source.
 */
export async function executeNodeRpc(
  nodeInput: unknown,
  method: string,
  params: Record<string, unknown> = {},
  timeout = 120_000,
): Promise<NodeCommandResult> {
  const input = nodeInput && typeof nodeInput === "object" ? nodeInput as Partial<ManagedNode> : null;
  assertValidation(input?.kind === "managed-node", "RPC 只能在受管节点执行");
  const node = normalizeNode(nodeInput);
  assertValidation(node.transport === "agent", "结构化 RPC 只能用于 Agent 节点");
  assertValidation(agentBroker !== null, "Agent 通信服务尚未初始化");
  const startedAt = Date.now();
  logger.info("开始执行 Agent 操作", { nodeId: node.id, method, timeoutMs: timeout });
  try {
    const result = await agentBroker.dispatch(node.id, method, params, timeout);
    const normalized = {
      ok: result.ok,
      stdout: String(result.stdout ?? "").trim(),
      stderr: String(result.stderr ?? "").trim(),
      ...(result.code === undefined ? {} : { code: result.code }),
    };
    logger.info("Agent 操作完成", {
      nodeId: node.id,
      method,
      ok: normalized.ok,
      code: normalized.code === undefined ? null : String(normalized.code),
      durationMs: Date.now() - startedAt,
    });
    return normalized;
  } catch (error) {
    logger.error("Agent 操作异常", { nodeId: node.id, method, durationMs: Date.now() - startedAt, ...errorContext(error) });
    throw error;
  }
}

interface ExecError extends ExecFileException {
  stdout?: string;
  stderr?: string;
}

interface ManagedSshConfiguration {
  identityFile: string | null;
  knownHostsFile: string | null;
}

const OPENSSH_INFORMATION_LINES = new Set([
  "** WARNING: connection is not using a post-quantum key exchange algorithm.",
  "** This session may be vulnerable to \"store now, decrypt later\" attacks.",
  "** The server may need to be upgraded. See https://openssh.com/pq.html",
]);

// Non-English or minimal remote images often emit this login-shell warning
// for every SSH command. It is environmental noise and must not hide the
// actual command error (for example, a route lookup returning no result).
const REMOTE_SHELL_INFORMATION_LINES = [
  /^(?:bash|sh): warning: setlocale.*cannot change locale/i,
];

let managedSshConfiguration: ManagedSshConfiguration = { identityFile: null, knownHostsFile: null };
let agentBroker: AgentBroker | null = null;

/** Install the controller-side broker used by nodes configured with transport=agent. */
export function configureAgentBroker(broker: AgentBroker): void { agentBroker = broker; }

function commandStderr(node: ManagedNode, value: unknown): string {
  const stderr = String(value ?? "").replace(/\r\n/g, "\n");
  if (node.transport !== "ssh") return stderr.trim();
  return stderr
    .split("\n")
    .filter((line) => !OPENSSH_INFORMATION_LINES.has(line))
    .filter((line) => !/^Warning: Permanently added .+ to the list of known hosts\.$/.test(line))
    .filter((line) => !REMOTE_SHELL_INFORMATION_LINES.some((pattern) => pattern.test(line)))
    .join("\n")
    .trim();
}

function validateExecutionOptions(command: string, options: NodeExecutorOptions): { timeout: number; maxBuffer: number } {
  assertValidation(typeof command === "string" && command.length > 0, "节点命令不能为空");
  assertValidation(!command.includes("\u0000"), "节点命令不能包含 NUL 字符");
  assertValidation(command.length <= MAX_NODE_COMMAND_LENGTH, "节点命令长度超出限制");
  if (options.input !== undefined) {
    assertValidation(typeof options.input === "string", "节点命令输入必须是字符串");
    assertValidation(!options.input.includes("\u0000"), "节点命令输入不能包含 NUL 字符");
    assertValidation(options.input.length <= MAX_NODE_INPUT_LENGTH, "节点命令输入长度超出限制");
  }
  const timeout = options.timeout ?? 15_000;
  const maxBuffer = options.maxBuffer ?? 2 * 1024 * 1024;
  assertValidation(Number.isSafeInteger(timeout) && timeout >= 250 && timeout <= MAX_NODE_TIMEOUT, "节点命令超时不合法");
  assertValidation(Number.isSafeInteger(maxBuffer) && maxBuffer >= 1024 && maxBuffer <= MAX_NODE_OUTPUT, "节点命令输出限制不合法");
  return { timeout, maxBuffer };
}

function sshArgs(node: ManagedNode, remoteCommand: string): string[] {
  const args = [
    "-o", "BatchMode=yes",
    "-o", "ConnectTimeout=8",
    // Host keys are still checked against the controller-managed file below.
    // accept-new only applies when a caller deliberately uses the legacy
    // identity mode without a managed known_hosts file.
    "-o", "StrictHostKeyChecking=accept-new",
    "-o", "HashKnownHosts=yes",
    "-o", "UpdateHostKeys=yes",
  ];
  if (managedSshConfiguration.identityFile) {
    args.push(
      "-o", "ControlMaster=auto",
      "-o", "ControlPersist=300",
      "-o", `ControlPath=${path.join(path.dirname(managedSshConfiguration.identityFile), "cm-%C")}`,
    );
  }
  if (node.sshPort !== 22) args.push("-p", String(node.sshPort));
  if (node.sshIdentity === "managed") {
    assertValidation(
      managedSshConfiguration.identityFile && managedSshConfiguration.knownHostsFile,
      "Birdbox 托管 SSH 密钥尚未初始化",
    );
    args.push(
      "-i", managedSshConfiguration.identityFile,
      "-o", `UserKnownHostsFile=${managedSshConfiguration.knownHostsFile}`,
      "-o", "IdentitiesOnly=yes",
    );
  }
  // The target and command are separate argv entries. No user-provided value
  // can become an OpenSSH option, and the command is sent only after `--`.
  const target = node.sshUser ? `${node.sshUser}@${node.sshHost}` : node.sshHost as string;
  const commandWithSystemPath = `PATH=/usr/sbin:/usr/bin:/sbin:/bin:$PATH; export PATH; ${remoteCommand}`;
  args.push("--", target, commandWithSystemPath);
  return args;
}

function execFileWithInput(
  executable: string,
  args: string[],
  options: ExecFileOptionsWithStringEncoding,
  input?: string,
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = execFile(executable, args, options, (error, stdout, stderr) => {
      if (error) {
        const execError = error as ExecError;
        execError.stdout = stdout;
        execError.stderr = stderr;
        reject(execError);
        return;
      }
      resolve({ stdout, stderr });
    });
    if (input !== undefined) {
      child.stdin?.on("error", () => {});
      child.stdin?.end(input);
    }
  });
}

export function configureManagedSsh({ identityFile, knownHostsFile }: { identityFile: string; knownHostsFile: string }): void {
  managedSshConfiguration = {
    identityFile: path.resolve(identityFile),
    knownHostsFile: path.resolve(knownHostsFile),
  };
}

/**
 * Execute one internally-generated node operation. HTTP callers must never
 * pass a command directly; they should call a typed operation in bird-runtime.
 * This compatibility boundary remains intentionally small and validates all
 * process limits before invoking execFile (never exec or a shell on the
 * controller side).
 */
export async function executeNodeCommand(
  nodeInput: unknown,
  command: string,
  options: NodeExecutorOptions = {},
): Promise<NodeCommandResult> {
  const input = nodeInput && typeof nodeInput === "object" ? nodeInput as Partial<ManagedNode> : null;
  assertValidation(input?.kind === "managed-node", "命令只能在受管节点执行");
  const node = normalizeNode(nodeInput);
  const { timeout, maxBuffer } = validateExecutionOptions(command, options);
  if (node.transport === "agent") {
    const result = await executeNodeRpc(node, "legacy.exec", {
      command,
      input: options.input ?? null,
      timeoutMs: timeout,
      maxBuffer,
    }, timeout + 10_000);
    return result;
  }
  const startedAt = Date.now();
  logger.info("开始执行节点命令", { nodeId: node.id, transport: node.transport, timeoutMs: timeout });
  try {
    const executable = node.transport === "local" ? "bash" : "ssh";
    const args = node.transport === "local"
      ? ["-lc", command]
      : sshArgs(node, command);
    const result = await execFileWithInput(executable, args, {
      timeout,
      maxBuffer,
      encoding: "utf8",
    }, options.input);
    const normalized = { ok: true, stdout: result.stdout.trim(), stderr: commandStderr(node, result.stderr) };
    logger.info("节点命令完成", { nodeId: node.id, transport: node.transport, ok: true, durationMs: Date.now() - startedAt });
    return normalized;
  } catch (error) {
    const execError = error as ExecError;
    const normalized = {
      ok: false,
      stdout: String(execError.stdout ?? "").trim(),
      stderr: commandStderr(node, execError.stderr ?? execError.message ?? "命令执行失败"),
      code: execError.code ?? 1,
    };
    logger.warn("节点命令失败", {
      nodeId: node.id,
      transport: node.transport,
      code: String(normalized.code),
      durationMs: Date.now() - startedAt,
      stderr: normalized.stderr.slice(0, 500),
    });
    return normalized;
  }
}

// Compatibility alias used by the existing BIRD runtime facade. New code
// should use executeNodeCommand or a typed operation wrapper instead.
export const runOnNode = executeNodeCommand;
